apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akstore-site-tls
spec:
  secretName: akstore-site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: akstore.site
  dnsNames:
    - akstore.site
    - www.akstore.site
