apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akstore-online-tls
spec:
  secretName: akstore-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: akstore.online
  dnsNames:
    - akstore.online
    - www.akstore.online
